In [21]:
import cvxpy as cp
import numpy as np

In [42]:
c = np.array([2, 11, 10])
mi = np.array([1, 2, 3])
vi = np.array([1, 4, 2])
M = np.array([1, 5, 8])
V = np.array([1, 9, 6])

In [68]:
#n = len(M) #len(V)
#m = len(mi) #len(v)
n = 10
m = 50
mi = np.random.rand(m)
vi = np.random.rand(m)
M = np.random.rand(n)*0.2*m
V = np.random.rand(n)*0.2*m
c = np.random.rand(n)
x = cp.Variable((m, n), boolean=True)
y = cp.Variable(n, boolean=True)

cons = [mi@x[:,i] <= M[i]*y[i] for i in range(n)] + \
        [vi@x[:,i] <= V[i]*y[i] for i in range(n)] + \
        [sum(x[i,:]) == 1 for i in range(m)]

prob = cp.Problem(cp.Minimize(c.T@y), cons)

In [69]:
M

array([1.70475097, 0.61006815, 4.8375929 , 1.73771278, 8.85699974,
       6.6505445 , 2.42273008, 8.7687896 , 7.2956546 , 2.1478456 ])

In [70]:
prob.solve()

1.998682175194499

In [71]:
y.value

array([-0.,  1., -0.,  0., -0.,  1.,  1.,  1.,  1.,  0.])

In [72]:
x.value

array([[-0.,  1.,  0., -0., -0., -0.,  0., -0., -0., -0.],
       [-0.,  0., -0., -0., -0., -0., -0.,  1., -0., -0.],
       [-0.,  0., -0., -0., -0., -0., -0.,  1., -0., -0.],
       [-0.,  0., -0., -0., -0., -0., -0.,  1., -0., -0.],
       [-0., -0., -0., -0., -0.,  1.,  0., -0., -0., -0.],
       [-0., -0., -0., -0., -0., -0., -0.,  1., -0., -0.],
       [-0.,  1., -0., -0., -0., -0., -0., -0., -0., -0.],
       [-0., -0., -0., -0., -0.,  1., -0., -0., -0., -0.],
       [-0.,  0., -0., -0., -0., -0., -0.,  1., -0., -0.],
       [-0.,  0., -0., -0., -0., -0.,  1., -0., -0., -0.],
       [-0.,  1., -0., -0., -0., -0., -0., -0., -0., -0.],
       [-0., -0., -0., -0., -0., -0., -0.,  1.,  0., -0.],
       [-0., -0., -0., -0., -0., -0.,  1., -0., -0., -0.],
       [-0.,  0., -0., -0., -0., -0., -0., -0.,  1., -0.],
       [-0., -0., -0., -0., -0.,  1., -0., -0., -0., -0.],
       [-0.,  0., -0., -0., -0., -0.,  1., -0., -0., -0.],
       [-0.,  0., -0., -0., -0., -0., -0.,  1., -0., -0.

In [73]:
prob.solver_stats.solve_time

0.14452552795410156