In [1]:
# Import packages.
import cvxpy as cp
import numpy as np

In [14]:
d = np.array([20,20,30,10])
xf = cp.Variable((3,4), boolean=True)
xc = cp.Variable((3,4), integer=True)
constraints = [cp.sum(xf[:,i]) == 1 for i in range(4)]
constraints += [cp.sum(xc[i,:]) <= 32 for i in range(3)]
constraints += [xc[:,i] <= d[i]*xf[:,i] for i in range(4)]
constraints += [xc >= 0]
objective = sum(d)-cp.sum(xc)
prob = cp.Problem(cp.Minimize(objective), constraints)
prob.solve(solver=cp.GUROBI)

0.0

In [15]:
# Print result.
print("\nThe optimal value is", prob.value)
print(xf.value)
print(xc.value)


The optimal value is 0.0
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 1.]]
[[20.  0.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0. 20.  0. 10.]]


In [3]:
# Generate a random non-trivial linear program.
m = 15
n = 10
np.random.seed(1)
s0 = np.random.randn(m)
lamb0 = np.maximum(-s0, 0)
s0 = np.maximum(s0, 0)
x0 = np.random.randn(n)
A = np.random.randn(m, n)
b = A@x0 + s0
c = -A.T@lamb0

# Define and solve the CVXPY problem.
x = cp.Variable(n)
prob = cp.Problem(cp.Minimize(c.T@x),
                 [A@x <= b])
prob.solve(solver=cp.GUROBI)

# Print result.
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)
print("A dual solution is")
print(prob.constraints[0].dual_value)

Academic license - for non-commercial use only

The optimal value is -15.220912604467836
A solution x is
[-1.10871865 -0.11841239 -0.99712988 -0.01927142  0.73027293 -1.26127757
  1.05265766  0.7802793   0.43064102  0.88633021]
A dual solution is
[-0.          0.61175641  0.52817175  1.07296862 -0.          2.3015387
 -0.          0.7612069   0.          0.24937038 -0.          2.06014071
  0.3224172   0.38405435 -0.        ]


In [2]:
cp.installed_solvers()

['ECOS', 'ECOS_BB', 'GUROBI', 'MOSEK', 'OSQP', 'SCS']